version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: simsapras-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: simsapras
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - simsapras-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: simsapras-backend
    restart: always
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/simsapras?schema=public
      JWT_SECRET: supersecret_docker_key
    depends_on:
      - db
    networks:
      - simsapras-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: simsapras-frontend
    restart: always
    ports:
      - '3001:3000'
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3000
    depends_on:
      - backend
    networks:
      - simsapras-network

volumes:
  postgres_data:

networks:
  simsapras-network:
    driver: bridge
